(function(){
'use strict';
const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
class InputManager{
 constructor(){this.keys=new Set();this.touches=new Map();this.edges={reset:false,pause:false};this.padPrevious={reset:false,pause:false};
  const controlled=['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight','KeyR','Escape'];
  window.addEventListener('keydown',e=>{if(!controlled.includes(e.code)||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;e.preventDefault();if(!this.keys.has(e.code)){if(e.code==='KeyR')this.edges.reset=true;if(e.code==='Escape')this.edges.pause=true;}this.keys.add(e.code);});
  window.addEventListener('keyup',e=>this.keys.delete(e.code));window.addEventListener('blur',()=>this.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden)this.clear();});
  document.querySelectorAll('[data-input]').forEach(b=>{b.addEventListener('contextmenu',e=>e.preventDefault());b.addEventListener('pointerdown',e=>{e.preventDefault();try{b.setPointerCapture(e.pointerId);}catch(_){}this.touches.set(e.pointerId,{action:b.dataset.input,button:b});b.classList.add('held');if(b.dataset.input==='reset')this.edges.reset=true;});const release=e=>{const touch=this.touches.get(e.pointerId);this.touches.delete(e.pointerId);if(touch&&![...this.touches.values()].some(t=>t.button===touch.button))touch.button.classList.remove('held');};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);});
 }
 clear(){this.keys.clear();this.touches.forEach(t=>t.button.classList.remove('held'));this.touches.clear();this.edges={reset:false,pause:false};}
 read(){const key=(...ks)=>ks.some(k=>this.keys.has(k)),touch=n=>[...this.touches.values()].some(t=>t.action===n);let gas=+(key('KeyW','ArrowUp')||touch('gas')),brake=+(key('KeyS','ArrowDown')||touch('brake')),steer=+(key('KeyD','ArrowRight')||touch('right'))-+(key('KeyA','ArrowLeft')||touch('left')),nitro=key('ShiftLeft','ShiftRight')||touch('nitro'),handbrake=key('Space')||touch('handbrake');let pad=null;try{pad=Array.from(navigator.getGamepads?navigator.getGamepads():[]).find(p=>p&&p.connected);}catch(_){}
  if(pad){const val=i=>pad.buttons[i]?.value||0,pressed=i=>!!pad.buttons[i]?.pressed;const axis=pad.axes[0]||0;if(Math.abs(axis)>.12&&Math.abs(axis)>Math.abs(steer))steer=Math.sign(axis)*(Math.abs(axis)-.12)/.88;gas=Math.max(gas,val(7));brake=Math.max(brake,val(6));nitro=nitro||pressed(0);handbrake=handbrake||pressed(1);const pause=pressed(9),reset=pressed(3);if(pause&&!this.padPrevious.pause)this.edges.pause=true;if(reset&&!this.padPrevious.reset)this.edges.reset=true;this.padPrevious={pause,reset};}else this.padPrevious={pause:false,reset:false};
  const result={gas,brake,steer,handbrake,nitro,reset:this.edges.reset,pause:this.edges.pause};this.edges.reset=false;this.edges.pause=false;return result;
 }
}
class AudioManager{
 constructor(){this.ctx=null;this.volume=.5;this.ready=false;this.lastLap=0;}
 start(){try{if(this.ctx){this.ctx.resume().catch(()=>{});return;}const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=this.volume*.22;this.master.connect(this.ctx.destination);this.engine=this.ctx.createOscillator();this.engine.type='sawtooth';this.engine.frequency.value=45;this.engineGain=this.ctx.createGain();this.engineGain.gain.value=0;this.filter=this.ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=350;this.engine.connect(this.filter);this.filter.connect(this.engineGain);this.engineGain.connect(this.master);this.engine.start();this.ready=true;this.ctx.resume().catch(()=>{});}catch(_){this.ready=false;}}
 setVolume(v){this.volume=clamp(Number(v)||0,0,1);if(this.ready)this.master.gain.setTargetAtTime(this.volume*.22,this.ctx.currentTime,.1);}
 update(car,state,dt){if(!this.ready||!car)return;try{const t=this.ctx.currentTime,active=state==='racing'||state==='countdown';const speed=Math.abs(car.speed||0);this.engine.frequency.setTargetAtTime(43+(speed%22)*3+speed*.9,t,.08);this.filter.frequency.setTargetAtTime(260+speed*13,t,.1);this.engineGain.gain.setTargetAtTime(active?.12+Math.min(speed/100,.25):0,t,.08);}catch(_){}}
 emit(event){if(!this.ready)return;try{const t=this.ctx.currentTime,osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.connect(gain);gain.connect(this.master);let freq=520,end=300,duration=.12,volume=.3;switch(event){case'countdown':case'beep':freq=600;end=600;break;case'go':case'start':freq=960;end=1200;duration=.3;break;case'lap':freq=620;end=1240;duration=.3;break;case'finish':case'win':freq=440;end=1760;duration=.8;break;case'collision':case'crash':case'hit':freq=95;end=30;duration=.2;osc.type='triangle';volume=.6;break;case'nitro':freq=160;end=700;duration=.35;volume=.12;break;default:freq=400;}osc.frequency.setValueAtTime(freq,t);osc.frequency.exponentialRampToValueAtTime(end,t+duration);gain.gain.setValueAtTime(volume,t);gain.gain.exponentialRampToValueAtTime(.001,t+duration);osc.start(t);osc.stop(t+duration+.03);osc.onended=()=>{osc.disconnect();gain.disconnect();};}catch(_){}}
}
class GameUI{
 constructor(game){this.game=game;this.carType='rally';this.difficulty='normal';this.lang='th';this.lastState=null;this.debug=false;this.fps=60;this.mapClock=0;this.dialog=null;this.countPrevious=null;try{const saved=JSON.parse(localStorage.getItem('dune-bolt-settings')||'null');if(saved){if(['th','en'].includes(saved.lang))this.lang=saved.lang;if(Number.isFinite(saved.volume))game.settings.volume=clamp(saved.volume,0,1);if(['auto','high','low'].includes(saved.quality))game.settings.quality=saved.quality;if(typeof saved.shake==='boolean')game.settings.shake=saved.shake;}}catch(_){}
  this.translate();$('volume').value=game.settings.volume??.5;$('quality').value=game.settings.quality||'high';$('shake').checked=game.settings.shake!==false;game.audio?.setVolume(Number($('volume').value));
  $('language').onclick=()=>{this.lang=this.lang==='th'?'en':'th';this.translate();this.save();};
  document.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>{this.carType=b.dataset.car;document.querySelectorAll('[data-car]').forEach(c=>c.classList.toggle('active',b===c));game.previewCarType=this.carType;});
  document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{this.difficulty=b.dataset.difficulty;document.querySelectorAll('[data-difficulty]').forEach(c=>c.classList.toggle('active',b===c));});
  $('play').onclick=()=>{game.audio?.start();this.closeDialogs();game.inputManager?.clear();game.start(this.carType,this.difficulty);};
  $('pause').onclick=()=>{game.inputManager?.clear();game.pause();};$('resume').onclick=()=>{game.audio?.start();game.inputManager?.clear();game.resume();};
  ['pause-restart','result-restart'].forEach(id=>$(id).onclick=()=>{this.closeDialogs();game.audio?.start();game.inputManager?.clear();game.restart();});['pause-menu','result-menu'].forEach(id=>$(id).onclick=()=>{this.closeDialogs();game.inputManager?.clear();game.toMenu();});
  $('open-settings').onclick=() => this.openDialog('settings');$('pause-settings').onclick=()=>this.openDialog('settings');$('open-help').onclick=()=>this.openDialog('help');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>this.closeDialogs());
  $('volume').oninput=e=>{game.audio?.start();game.settings.volume=Number(e.target.value);game.audio?.setVolume(game.settings.volume);this.save();};$('quality').onchange=e=>{game.settings.quality=e.target.value;this.save();};$('shake').onchange=e=>{game.settings.shake=e.target.checked;this.save();};
  window.addEventListener('keydown',e=>{if(e.code==='F2'){e.preventDefault();this.debug=!this.debug;$('debug').classList.toggle('hidden',!this.debug);}if(e.code==='Escape'&&this.dialog){this.closeDialogs();game.inputManager&&(game.inputManager.edges.pause=false);}});
  this.map=$('minimap').getContext('2d');$('loading').classList.add('hidden');if(game.track?.length)$('track-length').textContent=(game.track.length/1000).toFixed(2)+' KM';this.update(0);
 }
 translate(){document.documentElement.lang=this.lang;document.querySelectorAll('[data-th]').forEach(e=>e.innerHTML=e.dataset[this.lang]);$('language').textContent=this.lang==='th'?'TH / en':'th / EN';}
 save(){try{localStorage.setItem('dune-bolt-settings',JSON.stringify({...this.game.settings,lang:this.lang}));}catch(_){}}
 openDialog(name){this.dialog=name;$(name+'-modal').classList.remove('hidden');if(this.game.state==='paused')$('pause-modal').classList.add('hidden');$(name+'-modal').querySelector('button')?.focus();}
 closeDialogs(){this.dialog=null;$('settings-modal').classList.add('hidden');$('help-modal').classList.add('hidden');if(this.game.state==='paused')$('pause-modal').classList.remove('hidden');}
 format(s){if(!Number.isFinite(s)||s<=0)return'00:00.00';return String(Math.floor(s/60)).padStart(2,'0')+':'+(s%60).toFixed(2).padStart(5,'0');}
 update(dt){const g=this.game,c=g.cars?.[0],state=g.state;this.fps=this.fps*.94+(dt>0?1/dt:60)*.06;
  if(state!==this.lastState){this.lastState=state;this.closeDialogs();$('menu').classList.toggle('hidden',state!=='menu');$('masthead').classList.toggle('hidden',state!=='menu');$('hud').classList.toggle('hidden',state==='menu');$('pause-modal').classList.toggle('hidden',state!=='paused');$('results-modal').classList.toggle('hidden',state!=='finished');document.body.classList.toggle('driving',state==='racing'||state==='countdown');if(state==='paused')$('resume').focus();if(state==='finished'&&c){$('result-position').textContent=String(g.rank(c)).padStart(2,'0');$('result-time').textContent=this.format(c.finishTime||g.time);$('result-best').textContent=g.bestLap&&Number.isFinite(g.bestLap)?this.format(g.bestLap):'—';$('result-restart').focus();}}
  if(c&&state!=='menu'){$('position').textContent=g.rank(c);$('lap').textContent=Math.min(g.config?.laps||3,(c.lap||0)+1);$('time').textContent=this.format(c.finished?c.finishTime:g.time);$('best').textContent=g.bestLap&&Number.isFinite(g.bestLap)?this.format(g.bestLap):'—';$('speed').textContent=Math.round(Math.abs(c.speed||0)*3.6);const n=clamp((c.nitro??65)/100,0,1);$('nitro').style.transform='scaleX('+n+')';$('nitro-text').textContent=Math.round(n*100)+'%';}
  $('countdown').classList.toggle('hidden',state!=='countdown');if(state==='countdown'){$('countdown').textContent=Math.max(1,Math.ceil(g.countdown));}
  this.mapClock+=dt;if(this.mapClock>.08&&state!=='menu'){this.mapClock=0;this.drawMap();}if(this.debug)$('debug').textContent='FPS '+Math.round(this.fps)+'\nSTATE '+state+'\nSPEED '+(c?.speed||0).toFixed(1)+' m/s\nCHECKPOINT '+(c?.nextCheckpoint??0)+'\nLAP '+(c?.lap??0)+'\nQUALITY '+g.settings.quality;
 }
 drawMap(){const pts=this.game.track?.points;if(!pts?.length||!this.map)return;const ctx=this.map,w=300,h=260;ctx.clearRect(0,0,w,h);let minX=Infinity,minZ=Infinity,maxX=-Infinity,maxZ=-Infinity;for(const p of pts){minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minZ=Math.min(minZ,p.z);maxZ=Math.max(maxZ,p.z);}const scale=Math.min((w-42)/(maxX-minX||1),(h-62)/(maxZ-minZ||1)),ox=(w-(maxX-minX)*scale)/2,oz=(h-(maxZ-minZ)*scale)/2+9;const x=p=>(p.x-minX)*scale+ox,z=p=>(p.z-minZ)*scale+oz;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(x(p),z(p)):ctx.moveTo(x(p),z(p)));ctx.closePath();ctx.strokeStyle='#78806b';ctx.lineWidth=8;ctx.stroke();ctx.strokeStyle='#ececdd';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#26332b';ctx.fillRect(x(pts[0])-4,z(pts[0])-4,8,8);const cars=this.game.cars||[];for(let i=cars.length-1;i>=0;i--){const c=cars[i];ctx.beginPath();ctx.arc(x(c),z(c),i===0?7:5,0,Math.PI*2);ctx.fillStyle=i===0?'#fa572e':'#26332b';ctx.fill();ctx.strokeStyle='#f4eee2';ctx.lineWidth=2;ctx.stroke();}}
}
globalThis.InputManager=InputManager;globalThis.AudioManager=AudioManager;globalThis.GameUI=GameUI;
})();

