begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;
select plan(18);
select has_enum('public', 'community_category', 'community category enum exists');
select has_enum('public', 'media_purpose', 'media purpose enum exists');
select has_table('public', 'account_access', 'account access table exists');
select has_table('public', 'admin_audit_log', 'admin audit log exists');
select ok((select relrowsecurity from pg_class where oid = 'public.account_access'::regclass), 'account access has RLS');
select ok((select relrowsecurity from pg_class where oid = 'public.admin_audit_log'::regclass), 'admin audit log has RLS');
select col_not_null('public', 'posts', 'community_category', 'posts require a community category');
select col_hasnt_default('public', 'posts', 'community_category', 'posts do not retain a category default');
select ok(not exists (select 1 from pg_type t join pg_enum e on e.enumtypid=t.oid where t.typname='community_category' and e.enumlabel in ('photographers','market')), 'removed categories are absent');
select ok(not exists (select 1 from pg_type t join pg_enum e on e.enumtypid=t.oid where t.typname='media_purpose' and e.enumlabel='market'), 'removed media purpose is absent');
select ok(to_regclass('public.photographer_spots') is null, 'photographer spots table is absent');
select ok(to_regclass('public.market_products') is null, 'market products table is absent');
select ok(not exists (select 1 from information_schema.columns where table_schema='public' and table_name='post_marker_tags' and column_name='photographer_spot_id'), 'marker tags have no photographer foreign key');
select ok(not exists (select 1 from pg_enum e join pg_type t on t.oid=e.enumtypid where t.typname='marker_tag_type' and e.enumlabel <> 'event'), 'marker tags only support events');
select has_function('public', 'delete_admin_moderated_resource', array['uuid', 'uuid', 'text'], 'admin moderation delete function exists');
select has_function('public', 'save_post_with_markers', array['uuid','text','jsonb','community_category'], 'post save function exists');
select ok(not exists (select 1 from pg_policies where tablename in ('photographer_spots','market_products')), 'removed tables have no policies');
select ok(not exists (select 1 from pg_constraint where conname like '%photographer_spot%'), 'removed photographer constraints are absent');
select * from finish();
rollback;
