begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;
select plan(13);
select has_table('public', 'posts', 'posts table exists');
select has_table('public', 'events', 'events table exists');
select ok((select relrowsecurity from pg_class where oid = 'public.posts'::regclass), 'posts have RLS');
select ok((select relrowsecurity from pg_class where oid = 'public.events'::regclass), 'events have RLS');
select ok(to_regclass('public.photographer_spots') is null, 'photographer spots table is removed');
select ok(to_regclass('public.market_products') is null, 'market products table is removed');
select ok(not exists (select 1 from pg_type t join pg_enum e on e.enumtypid=t.oid where t.typname='community_category' and e.enumlabel in ('photographers','market')), 'removed categories are absent');
select ok(not exists (select 1 from information_schema.columns where table_schema='public' and table_name='post_marker_tags' and column_name='photographer_spot_id'), 'photographer marker foreign key is removed');
select ok(not exists (select 1 from pg_type t join pg_enum e on e.enumtypid=t.oid where t.typname='marker_tag_type' and e.enumlabel <> 'event'), 'only event marker tags remain');
select has_index('public', 'events', 'events_location_idx', 'events have a spatial index');
select has_function('public', 'save_post_with_markers', array['uuid','text','jsonb','community_category'], 'atomic post save function exists');
select has_column('public', 'posts', 'community_category', 'posts retain a category column');
select col_not_null('public', 'posts', 'community_category', 'posts require a community category');
select * from finish();
rollback;
