begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;
select plan(13);
select has_table('public', 'media', 'media table exists');
select has_table('public', 'media_variants', 'media variants table exists');
select has_table('public', 'vehicles', 'vehicles table exists');
select has_table('public', 'vehicle_media', 'vehicle media table exists');
select has_table('public', 'comments', 'comments table exists');
select has_table('public', 'post_marker_tags', 'post marker tags table exists');
select ok(to_regclass('public.market_products') is null, 'market products table is removed');
select ok(to_regclass('public.photographer_spots') is null, 'photographer spots table is removed');
select ok(not exists (select 1 from pg_type t join pg_enum e on e.enumtypid=t.oid where t.typname='media_purpose' and e.enumlabel='market'), 'market media enum value is removed');
select ok(not exists (select 1 from pg_proc where proname like '%photographer%'), 'photographer functions are removed');
select ok(not exists (select 1 from pg_proc where proname like '%market_product%'), 'market functions are removed');
select has_function('public', 'save_vehicle_with_media', array['uuid','jsonb','uuid[]'], 'atomic vehicle save function exists');
select has_function('public', 'delete_vehicle_permanently', array['uuid'], 'permanent vehicle delete function exists');
select * from finish();
rollback;
