"use client";
import { UploadSimple } from "@phosphor-icons/react";
import type { MediaPurpose } from "@iride/types";
import Image from "next/image";
import { useEffect,useState } from "react";
import { authorizeMediaAction,completeMediaAction } from "../../media-actions";
import type { Locale } from "@/lib/locale";

export function MediaUploader({cropRatio,locale,onReady,purpose}:{readonly cropRatio?:number;readonly locale:Locale;readonly onReady:(id:string)=>Promise<void>|void;readonly purpose:MediaPurpose}){
  const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[x,setX]=useState(50),[y,setY]=useState(50),[status,setStatus]=useState<string|null>(null),[pending,setPending]=useState(false);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  function choose(next:File|null){if(preview)URL.revokeObjectURL(preview);if(!next){setFile(null);setPreview(null);return}if(!["image/jpeg","image/png","image/webp"].includes(next.type)||next.size>10*1024*1024){setStatus(locale==="th"?"รองรับ JPG, PNG, WebP ไม่เกิน 10 MB":"Use JPG, PNG or WebP under 10 MB");return}setFile(next);setPreview(URL.createObjectURL(next));setStatus(null)}
  async function upload(){if(!file)return;setPending(true);try{const blob=cropRatio?await cropImage(file,cropRatio,x,y):file;const name=`${purpose}.${blob.type==="image/webp"?"webp":file.name.split(".").at(-1)??"jpg"}`;const auth=await authorizeMediaAction({filename:name,mimeType:blob.type||file.type,bytes:blob.size,purpose});const response=await fetch(auth.uploadUrl,{method:"PUT",headers:auth.headers,body:blob});if(!response.ok)throw new Error("MEDIA_UPLOAD_FAILED");let state=await completeMediaAction(auth.mediaId);for(let count=0;state.status!=="ready"&&count<30;count++){await new Promise((resolve)=>setTimeout(resolve,2000));state=await completeMediaAction(auth.mediaId)}if(state.status!=="ready")throw new Error("MEDIA_PROCESSING_TIMEOUT");await onReady(auth.mediaId);setStatus(locale==="th"?"อัปโหลดสำเร็จ":"Upload complete");setFile(null);setPreview(null)}catch{setStatus(locale==="th"?"อัปโหลดไม่สำเร็จ กรุณาลองใหม่":"Upload failed. Try again.")}finally{setPending(false)}}
  return <div className="media-uploader">{preview?<div className="crop-preview" style={{aspectRatio:cropRatio??1}}><Image alt="Preview" fill src={preview} style={{objectFit:"cover",objectPosition:`${x}% ${y}%`}} unoptimized/></div>:null}{preview&&cropRatio?<div className="crop-controls"><label>X<input max="100" min="0" onChange={(event)=>setX(Number(event.target.value))} type="range" value={x}/></label><label>Y<input max="100" min="0" onChange={(event)=>setY(Number(event.target.value))} type="range" value={y}/></label></div>:null}<label className="secondary-action"><UploadSimple size={17}/>{locale==="th"?"เลือกรูป":"Choose image"}<input accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={(event)=>choose(event.target.files?.[0]??null)} type="file"/></label>{file?<button className="primary-action" disabled={pending} onClick={upload} type="button">{pending?(locale==="th"?"กำลังประมวลผล…":"Processing…"):(locale==="th"?"อัปโหลดรูปนี้":"Upload this image")}</button>:null}{status?<p aria-live="polite">{status}</p>:null}</div>;
}

async function cropImage(file:File,ratio:number,x:number,y:number){const bitmap=await createImageBitmap(file);const sourceRatio=bitmap.width/bitmap.height;let width=bitmap.width,height=bitmap.height;if(sourceRatio>ratio)width=height*ratio;else height=width/ratio;const left=Math.max(0,Math.min(bitmap.width-width,(bitmap.width-width)*x/100)),top=Math.max(0,Math.min(bitmap.height-height,(bitmap.height-height)*y/100));const maxWidth=ratio===1?1024:1800,outputWidth=Math.min(maxWidth,Math.round(width)),outputHeight=Math.round(outputWidth/ratio),canvas=document.createElement("canvas");canvas.width=outputWidth;canvas.height=outputHeight;canvas.getContext("2d")!.drawImage(bitmap,left,top,width,height,0,0,outputWidth,outputHeight);bitmap.close();return new Promise<Blob>((resolve,reject)=>canvas.toBlob((blob)=>blob?resolve(blob):reject(new Error("CROP_FAILED")),"image/webp",.9))}
