"use client";

import { Camera,ChatCircle,MapPin,NotePencil,Storefront,Trash,UsersThree } from "@phosphor-icons/react";
import type { CommentDto,ContentAuthorDto,MarketProductDto,PhotographerSpotDto,PostDto } from "@iride/types";
import Image from "next/image";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useMemo,useState,type FormEvent } from "react";

import { communityRooms,type CommunityRoomId } from "@/lib/app-navigation-domain";
import { getComments,mediaVariantUrl } from "@/lib/content-api";
import type { Locale } from "@/lib/locale";
import { commentAction } from "../community/actions";
import { removeContent,removeMarketAction } from "../create/actions";
import { BackendForm,MarketForm,type MarkerOption } from "./create-content-screen";
import { EditModal } from "./edit-modal";

interface Props{readonly authenticated:boolean;readonly locale:Locale;readonly markerOptions:readonly MarkerOption[];readonly posts:readonly PostDto[];readonly products:readonly MarketProductDto[];readonly spots:readonly PhotographerSpotDto[];readonly viewer:ContentAuthorDto|null}
export function CommunityScreen({authenticated,locale,markerOptions,posts,products,spots,viewer}:Props){
  const params=useSearchParams(),requested=params.get("room"),room:CommunityRoomId=communityRooms.some((item)=>item.id===requested)?requested as CommunityRoomId:"talk";
  const editId=params.get("modal")==="edit"?(room==="talk"?params.get("post"):room==="market"?params.get("product"):null):null;
  const editPost=editId?posts.find((item)=>item.id===editId&&item.canEdit)??null:null;
  const editProduct=editId?products.find((item)=>item.id===editId&&item.canEdit)??null:null;
  return <div className="community-page"><header className="community-heading"><p className="premium-kicker">iRide Community</p><h1>{locale==="th"?"ชุมชนของคนรักการเดินทาง":"A community built around movement"}</h1></header><nav aria-label={locale==="th"?"ห้องชุมชน":"Community rooms"} className="community-rooms">{communityRooms.map((item)=><Link aria-current={item.id===room?"page":undefined} href={`/community?room=${item.id}`} key={item.id}>{item.label[locale]}</Link>)}</nav>
    {room==="talk"?<TalkRoom authenticated={authenticated} locale={locale} posts={posts} viewer={viewer}/>:null}
    {room==="market"?<MarketRoom locale={locale} products={products}/>:null}
    {room==="photographers"?<PhotographerRoom locale={locale} spots={spots}/>:null}
    {room==="groups"?<GroupsRoom locale={locale}/>:null}
    {editPost?<EditModal closeUrl={`/community?room=talk&post=${editPost.id}`} title={locale==="th"?"แก้ไขโพสต์":"Edit post"}><BackendForm initial={editPost} locale={locale} markerOptions={markerOptions} type="post"/></EditModal>:null}
    {editProduct?<EditModal closeUrl={`/community?room=market&product=${editProduct.id}`} title={locale==="th"?"แก้ไขสินค้า":"Edit product"}><MarketForm initial={editProduct} locale={locale}/></EditModal>:null}
  </div>;
}

function TalkRoom({authenticated,locale,posts,viewer}:{readonly authenticated:boolean;readonly locale:Locale;readonly posts:readonly PostDto[];readonly viewer:ContentAuthorDto|null}){return <section className="community-feed"><Link className="community-create-link" href="/create?type=post">+ {locale==="th"?"เขียนโพสต์":"Write a post"}</Link>{posts.length?posts.map((post)=><article className="premium-card community-post" id={`post-${post.id}`} key={post.id}><header><Link href={`/users/${post.author.username}`}>{post.author.displayName}</Link><span>@{post.author.username}</span></header><p>{post.body}</p>{post.markerTags.length?<div className="post-marker-tags">{post.markerTags.map((tag)=>tag.available?<Link href={`/?marker=${tag.id}`} key={`${tag.kind}:${tag.id}`}><MapPin size={15}/>{tag.title}</Link>:<span aria-disabled="true" key={`${tag.kind}:${tag.id}`}><MapPin size={15}/>{locale==="th"?"ไม่พบ marker":"Marker unavailable"}</span>)}</div>:null}<footer><time dateTime={post.createdAt}>{new Intl.DateTimeFormat(locale==="th"?"th-TH":"en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(post.createdAt))}</time><span><ChatCircle size={15}/>{post.commentCount}</span>{post.canEdit?<><Link href={`/community?room=talk&post=${post.id}&modal=edit`}><NotePencil size={15}/>{locale==="th"?"แก้ไข":"Edit"}</Link><form action={removeContent} onSubmit={(event)=>{if(!confirm(locale==="th"?"ลบโพสต์นี้หรือไม่?":"Delete this post?"))event.preventDefault()}}><input name="domain" type="hidden" value="posts"/><input name="id" type="hidden" value={post.id}/><button type="submit"><Trash size={15}/>{locale==="th"?"ลบ":"Delete"}</button></form></>:null}</footer><CommentThread authenticated={authenticated} locale={locale} postId={post.id} viewer={viewer}/></article>):<Empty text={locale==="th"?"ยังไม่มีโพสต์ เริ่มบทสนทนาแรกได้เลย":"No posts yet. Start the first conversation."}/>}</section>}

function CommentThread({authenticated,locale,postId,viewer}:{readonly authenticated:boolean;readonly locale:Locale;readonly postId:string;readonly viewer:ContentAuthorDto|null}){
  const [open,setOpen]=useState(false),[items,setItems]=useState<CommentDto[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null),[replyTo,setReplyTo]=useState<CommentDto|null>(null),[editing,setEditing]=useState<string|null>(null);
  async function load(){setLoading(true);try{setItems(await getComments(postId));setError(null)}catch{setError(locale==="th"?"โหลดความคิดเห็นไม่สำเร็จ":"Could not load comments")}finally{setLoading(false)}}
  function toggle(){const next=!open;setOpen(next);if(next&&!items.length)void load()}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),body=String(data.get("body")??"").trim();if(!body)return;const tempId=`temp-${Date.now()}`;if(viewer)setItems((current)=>[...current,{id:tempId,postId,body,author:viewer,parentId:replyTo?.parentId??replyTo?.id??null,replyTo:replyTo?.author??null,deleted:false,canEdit:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]);form.reset();setReplyTo(null);try{await commentAction(data);await load()}catch{setItems((current)=>current.filter((item)=>item.id!==tempId));setError(locale==="th"?"ส่งความคิดเห็นไม่สำเร็จ":"Comment failed")}}
  async function mutate(data:FormData){try{await commentAction(data);setEditing(null);await load()}catch{setError(locale==="th"?"บันทึกไม่สำเร็จ":"Update failed")}}
  const roots=useMemo(()=>items.filter((item)=>!item.parentId),[items]);
  return <div className="comment-thread"><button aria-expanded={open} className="comment-toggle" onClick={toggle} type="button"><ChatCircle size={17}/>{locale==="th"?"ความคิดเห็น":"Comments"}</button>{open?<div>{loading&&!items.length?<p role="status">{locale==="th"?"กำลังโหลด…":"Loading…"}</p>:null}{error?<p className="inline-error" role="alert">{error}</p>:null}{roots.map((comment)=><CommentItem comment={comment} editing={editing} items={items} key={comment.id} locale={locale} mutate={mutate} onEdit={setEditing} onReply={setReplyTo}/>)}{authenticated?<form className="comment-composer" onSubmit={submit}><input name="intent" type="hidden" value="create"/><input name="postId" type="hidden" value={postId}/><input name="parentId" type="hidden" value={replyTo?.id??""}/>{replyTo?<small>{locale==="th"?"ตอบกลับ":"Replying to"} @{replyTo.author.username} <button onClick={()=>setReplyTo(null)} type="button">×</button></small>:null}<textarea maxLength={1000} name="body" placeholder={locale==="th"?"เขียนความคิดเห็น…":"Write a comment…"} required/><button className="primary-action" type="submit">{locale==="th"?"ส่ง":"Send"}</button></form>:<Link href={`/login?next=${encodeURIComponent(`/community?room=talk&post=${postId}`)}`}>{locale==="th"?"เข้าสู่ระบบเพื่อแสดงความคิดเห็น":"Sign in to comment"}</Link>}</div>:null}</div>;
}

interface CommentItemProps{readonly comment:CommentDto;readonly editing:string|null;readonly items:readonly CommentDto[];readonly locale:Locale;readonly mutate:(data:FormData)=>Promise<void>;readonly onEdit:(id:string|null)=>void;readonly onReply:(item:CommentDto)=>void}
function CommentItem({comment,editing,items,locale,mutate,onEdit,onReply}:CommentItemProps){const replies=items.filter((item)=>item.parentId===comment.id);return <div className="comment-item"><CommentBody comment={comment} editing={editing} locale={locale} mutate={mutate} onEdit={onEdit} onReply={onReply}/>{replies.map((reply)=><div className="comment-reply" key={reply.id}><CommentBody comment={reply} editing={editing} locale={locale} mutate={mutate} onEdit={onEdit} onReply={onReply}/></div>)}</div>}
function CommentBody({comment,editing,locale,mutate,onEdit,onReply}:{readonly comment:CommentDto;readonly editing:string|null;readonly locale:Locale;readonly mutate:(data:FormData)=>Promise<void>;readonly onEdit:(id:string|null)=>void;readonly onReply:(item:CommentDto)=>void}){return <div><strong>@{comment.author.username}</strong>{comment.replyTo?<small> → @{comment.replyTo.username}</small>:null}{editing===comment.id?<form action={mutate}><input name="intent" type="hidden" value="update"/><input name="id" type="hidden" value={comment.id}/><textarea defaultValue={comment.body??""} maxLength={1000} name="body" required/><button type="submit">{locale==="th"?"บันทึก":"Save"}</button><button onClick={()=>onEdit(null)} type="button">{locale==="th"?"ยกเลิก":"Cancel"}</button></form>:<p>{comment.deleted?(locale==="th"?"ความคิดเห็นถูกลบแล้ว":"Comment deleted"):comment.body}</p>}{!comment.deleted?<div className="comment-actions"><button onClick={()=>onReply(comment)} type="button">{locale==="th"?"ตอบกลับ":"Reply"}</button>{comment.canEdit?<><button onClick={()=>onEdit(comment.id)} type="button">{locale==="th"?"แก้ไข":"Edit"}</button><form action={mutate}><input name="intent" type="hidden" value="delete"/><input name="id" type="hidden" value={comment.id}/><button type="submit">{locale==="th"?"ลบ":"Delete"}</button></form></>:null}</div>:null}</div>}

function MarketRoom({locale,products}:{readonly locale:Locale;readonly products:readonly MarketProductDto[]}){const params=useSearchParams();return <section><div className="room-action-row"><p>{locale==="th"?"สินค้าจากสมาชิก iRide":"Items from iRide members"}</p><Link href="/create?type=market">+ {locale==="th"?"ลงขายสินค้า":"Sell an item"}</Link></div><div className="product-grid">{products.map((product)=>{const selected=params.get("product")===product.id;return <article className={`product-card ${selected?"is-selected":""}`} id={`product-${product.id}`} key={product.id}><div className="product-media"><Image alt="" height={480} src={product.coverMediaId?mediaVariantUrl(product.coverMediaId,"thumbnail"):"/media/market-gear.webp"} unoptimized={Boolean(product.coverMediaId)} width={480}/><span>{product.category}</span></div><div className="p-3"><h2>{product.name}</h2><p>{new Intl.NumberFormat(locale==="th"?"th-TH":"en-US",{style:"currency",currency:"THB"}).format(product.priceSatang/100)}</p><Link href={`/users/${product.owner.username}`}>@{product.owner.username}</Link>{product.canEdit?<div className="owner-actions"><Link href={`/community?room=market&product=${product.id}&modal=edit`}><NotePencil size={16}/>{locale==="th"?"แก้ไข":"Edit"}</Link><form action={removeMarketAction}><input name="id" type="hidden" value={product.id}/><button type="submit"><Trash size={16}/>{locale==="th"?"ลบ":"Delete"}</button></form></div>:<Link href={`/community?room=market&product=${product.id}`}><Storefront size={17}/>{locale==="th"?"ดูสินค้า":"View"}</Link>}</div></article>})}</div></section>}
function PhotographerRoom({locale,spots}:{readonly locale:Locale;readonly spots:readonly PhotographerSpotDto[]}){const people=Array.from(new Map(spots.map((spot)=>[spot.photographer.username,spot.photographer])).values());return <section className="room-card-grid">{people.length?people.map((person)=><Link className="premium-card room-person-card" href={`/users/${person.username}`} key={person.username}><Camera size={24}/><strong>{person.displayName}</strong><span>@{person.username}</span></Link>):<Empty text={locale==="th"?"ยังไม่มีช่างภาพที่ลง landmark":"No photographers have published a landmark yet."}/>}</section>}
function GroupsRoom({locale}:{readonly locale:Locale}){return <section className="room-card-grid">{["Bangkok Weekend Riders","Classic Car Thailand","City Bicycle Crew"].map((name)=><article className="premium-card room-person-card" key={name}><UsersThree size={24}/><strong>{name}</strong><span>{locale==="th"?"กลุ่มเดโม":"Demo group"}</span></article>)}</section>}
function Empty({text}:{readonly text:string}){return <div className="empty-state"><strong>{text}</strong></div>}
