"use client";

import { CalendarBlank, Car, Check, Flag, MapPin, Motorcycle, Path, UsersThree, Bicycle } from "@phosphor-icons/react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { createActivity, validateCreateActivity, type CreateActivityInput, type VehicleKind } from "@/lib/activity-domain";
import type { Locale } from "@/lib/locale";
import { useMockApp } from "./mock-app-provider";

const initial: CreateActivityInput = { kind:"meeting", title:"", locationLabel:"", startsAt:"", summary:"", vehicleKinds:[] };
const kinds = [{value:"meeting" as const,icon:UsersThree},{value:"event" as const,icon:CalendarBlank},{value:"trip" as const,icon:Path}];

export function CreateActivityScreen({locale}:{readonly locale:Locale}) {
  const router=useRouter(); const {dispatch}=useMockApp(); const [step,setStep]=useState(1); const [form,setForm]=useState<CreateActivityInput>(initial); const [errors,setErrors]=useState<Record<string,string>>({});
  const t=locale==="th"?{eyebrow:"สร้างกิจกรรม",title:"เริ่มจากไอเดีย แล้วเจอกันจริง",detail:"จัด Meeting, Event หรือ Trip สำหรับรถยนต์ มอเตอร์ไซค์ และจักรยาน",next:"ถัดไป",back:"ย้อนกลับ",publish:"สร้างกิจกรรม",types:{meeting:"นัดพบ",event:"อีเวนต์",trip:"ทริป"}}:{eyebrow:"Create activity",title:"Turn an idea into a real meetup",detail:"Organize a Meeting, Event or Trip for cars, motorcycles and bicycles.",next:"Continue",back:"Back",publish:"Create activity",types:{meeting:"Meeting",event:"Event",trip:"Trip"}};
  function update<K extends keyof CreateActivityInput>(key:K,value:CreateActivityInput[K]){setForm(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:""}))}
  function submit(){const nextErrors=validateCreateActivity(form);setErrors(nextErrors);if(Object.keys(nextErrors).length){setStep(2);return;}const activity=createActivity(form);dispatch({type:"create-activity",activity});router.push(`/?activity=${activity.id}`)}
  return <div className="create-page"><div className="create-intro"><p className="premium-kicker">{t.eyebrow}</p><h1>{t.title}</h1><p>{t.detail}</p><div className="step-line"><span className={step>=1?"active":""}/><span className={step>=2?"active":""}/><span className={step>=3?"active":""}/></div></div><section className="create-card premium-card">
    {step===1?<><h2>{locale==="th"?"คุณกำลังจัดอะไร?":"What are you organizing?"}</h2><div className="kind-options">{kinds.map(({value,icon:Icon})=><button aria-pressed={form.kind===value} onClick={()=>update("kind",value)} key={value} type="button"><Icon size={27}/><strong>{t.types[value]}</strong><span>{value==="meeting"?(locale==="th"?"นัดเจอแบบเรียบง่าย":"A simple get-together"):value==="event"?(locale==="th"?"กิจกรรมที่มีรายละเอียด":"A scheduled program"):(locale==="th"?"เดินทางไปด้วยกัน":"Move together")}</span>{form.kind===value?<Check size={18}/>:null}</button>)}</div><button className="primary-action w-full" onClick={()=>setStep(2)} type="button">{t.next}</button></>:null}
    {step===2?<><h2>{locale==="th"?"รายละเอียดกิจกรรม":"Activity details"}</h2><div className="form-stack"><Field error={errors.title} label={locale==="th"?"ชื่อกิจกรรม":"Title"}><input value={form.title} onChange={e=>update("title",e.target.value)} placeholder="Riverside Sunday"/></Field><Field error={errors.locationLabel} label={locale==="th"?"จุดนัดพบ":"Meeting point"}><div className="input-icon"><MapPin size={18}/><input value={form.locationLabel} onChange={e=>update("locationLabel",e.target.value)} placeholder="Rama VIII Bridge"/></div></Field>{form.kind==="trip"?<Field error={errors.destinationLabel} label={locale==="th"?"จุดหมาย":"Destination"}><div className="input-icon"><Flag size={18}/><input value={form.destinationLabel??""} onChange={e=>update("destinationLabel",e.target.value)} placeholder="Khao Yai"/></div></Field>:null}<Field error={errors.startsAt} label={locale==="th"?"วันและเวลา":"Date and time"}><input type="datetime-local" value={form.startsAt} onChange={e=>update("startsAt",e.target.value)}/></Field><Field label={locale==="th"?"รายละเอียด":"Description"}><textarea value={form.summary} onChange={e=>update("summary",e.target.value)} placeholder={locale==="th"?"บอกคนอื่นว่าควรเตรียมอะไร…":"What should people know?"}/></Field></div><div className="form-actions"><button onClick={()=>setStep(1)} type="button">{t.back}</button><button className="primary-action" onClick={()=>setStep(3)} type="button">{t.next}</button></div></>:null}
    {step===3?<><h2>{locale==="th"?"Vehicle แบบไหนเข้าร่วมได้?":"Which vehicles can join?"}</h2><div className="vehicle-options">{(["car","motorcycle","bicycle"] as VehicleKind[]).map(kind=>{const Icon=kind==="car"?Car:kind==="motorcycle"?Motorcycle:Bicycle;const selected=form.vehicleKinds.includes(kind);return <button aria-pressed={selected} onClick={()=>update("vehicleKinds",selected?form.vehicleKinds.filter(item=>item!==kind):[...form.vehicleKinds,kind])} type="button" key={kind}><Icon size={24}/><span>{kind}</span>{selected?<Check size={17}/>:null}</button>})}</div>{errors.vehicleKinds?<p className="field-error">{errors.vehicleKinds}</p>:null}<div className="create-review"><strong>{form.title|| (locale==="th"?"ยังไม่ได้ตั้งชื่อ":"Untitled activity")}</strong><span>{form.locationLabel||"—"} · {form.startsAt?new Date(form.startsAt).toLocaleString(locale==="th"?"th-TH":"en-GB"):"—"}</span></div><div className="form-actions"><button onClick={()=>setStep(2)} type="button">{t.back}</button><button className="primary-action" onClick={submit} type="button">{t.publish}</button></div></>:null}
  </section></div>;
}

function Field({label,error,children}:{label:string;error?:string|undefined;children:React.ReactNode}){return <label className="form-field"><span>{label}</span>{children}{error?<small>{error}</small>:null}</label>}
