"use client";

import { Bell, Bicycle, Car, Check, Heart, MapPin, Motorcycle, PaperPlaneTilt, ShoppingBagOpen, UserPlus, UsersThree } from "@phosphor-icons/react";
import { useSearchParams } from "next/navigation";
import { useState } from "react";

import type { Locale } from "@/lib/locale";
import { activities, notifications, products, vehicles } from "@/lib/mock-content";
import type { VehicleKind } from "@/lib/activity-domain";
import { useMockApp } from "./mock-app-provider";

const shell = "mx-auto w-full max-w-[1180px] px-4 py-5 sm:px-6 sm:py-8";

export function CommunityScreen({ locale }: { readonly locale: Locale }) {
  const { state, dispatch } = useMockApp();
  const [body, setBody] = useState("");
  const [filter, setFilter] = useState("all");
  const posts = [{ id: "fixture-1", body: locale === "th" ? "เย็นนี้มีใครไป Riverside Meetup บ้าง? ผมเอาจักรยานไปครับ" : "Who is heading to the Riverside Meetup tonight? I’m bringing the bicycle.", createdAt: "18m" }, ...state.posts];
  function publish() { const value = body.trim(); if (!value) return; dispatch({ type: "create-post", post: { id: `post-${Date.now()}`, body: value, createdAt: locale === "th" ? "เมื่อสักครู่" : "Just now" } }); setBody(""); }
  return <div className={shell}><PageHeading eyebrow="iRide Community" title={locale === "th" ? "คุยกับคนที่ชอบการเดินทาง" : "Share the way you move"} detail={locale === "th" ? "โพสต์เรื่องราว นัดเจอ และแลกเปลี่ยนไอเดีย โดยไม่มีห้องแชต" : "Post stories, meeting ideas and moments—without chat clutter."}/>
    <div className="content-grid mt-6"><div className="space-y-4"><section className="premium-card p-4"><div className="flex gap-3"><Avatar initials="YO"/><label className="flex-1"><span className="sr-only">{locale === "th" ? "สร้างโพสต์" : "Create post"}</span><textarea className="composer-input" placeholder={locale === "th" ? "กำลังคิดอะไรเกี่ยวกับการเดินทาง?" : "What is moving you today?"} value={body} onChange={(event) => setBody(event.target.value)}/></label></div><div className="mt-3 flex justify-end"><button className="primary-action inline-flex items-center gap-2" disabled={!body.trim()} onClick={publish} type="button"><PaperPlaneTilt size={17}/>{locale === "th" ? "โพสต์" : "Post"}</button></div></section>
    <div className="filter-rail !px-0">{(["all","following","nearby"] as const).map((value)=><button aria-pressed={filter===value} key={value} onClick={()=>setFilter(value)} type="button">{locale === "th" ? ({all:"ทั้งหมด",following:"กำลังติดตาม",nearby:"ใกล้ฉัน"} as const)[value] : capitalize(value)}</button>)}</div>
    {posts.map((post)=><article className="premium-card p-4" key={post.id}><header className="flex items-center gap-3"><Avatar initials={post.id.startsWith("post-")?"YO":"NM"}/><div><strong className="text-sm">{post.id.startsWith("post-") ? (locale === "th" ? "คุณ" : "You") : "Narin Motion"}</strong><p className="text-xs text-muted-foreground">{post.createdAt}</p></div></header><p className="mt-4 text-sm leading-6 text-foreground/90">{post.body}</p><footer className="mt-4 flex gap-2 border-t border-border pt-3"><button className="social-action" type="button"><Heart size={17}/>{locale === "th" ? "ถูกใจ" : "Like"}</button><button className="social-action" type="button"><UsersThree size={17}/>{locale === "th" ? "ชวนเพื่อน" : "Invite"}</button></footer></article>)}</div>
    <aside className="premium-card hidden h-fit p-4 lg:block"><p className="premium-kicker">{locale === "th" ? "กำลังเกิดขึ้น" : "Happening soon"}</p>{activities.slice(0,3).map((item)=><a className="mt-3 flex gap-3 border-t border-border pt-3" href={`/?activity=${item.id}`} key={item.id}><MapPin className="mt-1 shrink-0 text-primary" size={18}/><span><strong className="block text-sm">{item.title}</strong><small className="text-muted-foreground">{item.locationLabel}</small></span></a>)}</aside></div>
  </div>;
}

export function MarketScreen({ locale }: { readonly locale: Locale }) {
  const { state, dispatch } = useMockApp(); const params=useSearchParams();
  const [filter,setFilter]=useState<"all"|VehicleKind>("all"); const [query,setQuery]=useState("");
  const visible=products.filter((p)=>(filter==="all"||p.vehicleKinds.includes(filter))&&p.name.toLowerCase().includes(query.toLowerCase()));
  return <div className={shell}><PageHeading eyebrow="iRide Market" title={locale === "th" ? "อุปกรณ์สำหรับทุก Vehicle" : "Gear for every vehicle"} detail={locale === "th" ? "คัดสรรของสำหรับรถยนต์ มอเตอร์ไซค์ และจักรยานอย่างสมดุล" : "Curated essentials for cars, motorcycles and bicycles."}/><label className="market-search mt-6"><span className="sr-only">Search products</span><input placeholder={locale === "th"?"ค้นหาสินค้า…":"Search products…"} value={query} onChange={(e)=>setQuery(e.target.value)}/></label><div className="filter-rail !px-0 !py-4">{(["all","car","motorcycle","bicycle"] as const).map((value)=><button aria-pressed={filter===value} onClick={()=>setFilter(value)} key={value} type="button">{vehicleIcon(value)}{locale==="th"?({all:"ทั้งหมด",car:"รถยนต์",motorcycle:"มอเตอร์ไซค์",bicycle:"จักรยาน"} as const)[value]:capitalize(value)}</button>)}</div><div className="product-grid">{visible.map((product)=>{const selected=state.selectedProductIds.includes(product.id)||params.get("product")===product.id;return <article className={`product-card ${selected?"is-selected":""}`} key={product.id}><div className="product-media"><img alt="" src={product.image}/><span>{product.category}</span></div><div className="p-3"><h2>{product.name}</h2><p>{product.price}</p><button aria-pressed={selected} onClick={()=>dispatch({type:"toggle-product",productId:product.id})} type="button">{selected?<Check size={17}/>:<ShoppingBagOpen size={17}/>} {selected?(locale==="th"?"เลือกแล้ว":"Selected"):(locale==="th"?"เลือกสินค้า":"Select")}</button></div></article>})}</div></div>;
}

export function ProfileOverview({ locale }: { readonly locale: Locale }) {
  const [tab,setTab]=useState<"overview"|"garage"|"activities">("overview");
  const nextActivity = activities[0]!;
  return <div className={shell}><section className="profile-hero premium-card"><div className="profile-cover"/><div className="profile-summary"><Avatar initials="RX" large/><div><p className="premium-kicker">@riderxplorer</p><h1>RiderXplorer</h1><p>Chiang Mai, Thailand · Car · Motorcycle · Bicycle</p></div><a href="/profile/edit">{locale==="th"?"แก้ไขโปรไฟล์":"Edit profile"}</a></div><div className="profile-stats"><span><strong>120</strong>{locale==="th"?"โพสต์":"Posts"}</span><span><strong>15.8K</strong>{locale==="th"?"ผู้ติดตาม":"Followers"}</span><span><strong>3</strong>Vehicles</span></div></section><div className="profile-tabs" role="tablist">{(["overview","garage","activities"] as const).map(value=><button aria-selected={tab===value} onClick={()=>setTab(value)} role="tab" key={value}>{locale==="th"?({overview:"ภาพรวม",garage:"Garage",activities:"กิจกรรม"} as const)[value]:capitalize(value)}</button>)}</div>{tab==="garage"?<section><div className="section-heading"><div><p className="premium-kicker">Garage</p><h2>{locale==="th"?"Vehicle ของฉัน":"My vehicles"}</h2></div></div><div className="vehicle-grid">{vehicles.map(vehicle=><article className="vehicle-card premium-card" key={vehicle.id}><img alt={vehicle.name} src={vehicle.image}/><div><span className="kind-badge kind-meeting">{vehicle.kind}</span><h3>{vehicle.name}</h3><p>{vehicle.nickname} · {vehicle.detail}</p></div></article>)}</div></section>:tab==="activities"?<div className="activity-list !grid">{activities.slice(0,3).map(item=><a className="activity-list-card" href={`/?activity=${item.id}`} key={item.id}><img alt="" src={item.image}/><div><span className={`kind-badge kind-${item.kind}`}>{item.kind}</span><strong>{item.title}</strong><span><MapPin size={14}/>{item.locationLabel}</span></div></a>)}</div>:<section className="profile-overview-grid"><article className="premium-card p-5"><p className="premium-kicker">{locale==="th"?"เกี่ยวกับ":"About"}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">{locale==="th"?"ออกไปพบผู้คนและเส้นทางใหม่ ๆ ด้วย Vehicle ทุกประเภท":"Finding new people and places through every kind of vehicle."}</p></article><article className="premium-card p-5"><p className="premium-kicker">{locale==="th"?"กิจกรรมถัดไป":"Next activity"}</p><h2 className="mt-2 font-black">{nextActivity.title}</h2><p className="mt-1 text-sm text-muted-foreground">{nextActivity.locationLabel}</p></article></section>}</div>;
}

export function NotificationsScreen({ locale }: { readonly locale: Locale }) { const {state,dispatch}=useMockApp();const unread=notifications.filter(n=>!state.readNotificationIds.includes(n.id));return <div className={`${shell} max-w-3xl`}><div className="flex items-end justify-between gap-4"><PageHeading eyebrow="iRide" title={locale==="th"?"การแจ้งเตือน":"Notifications"} detail={locale==="th"?`${unread.length} รายการใหม่`:`${unread.length} new`}/><button className="text-xs font-bold text-primary" onClick={()=>dispatch({type:"read-all-notifications",notificationIds:notifications.map(n=>n.id)})} type="button">{locale==="th"?"อ่านทั้งหมด":"Mark all read"}</button></div><div className="mt-6 space-y-2">{notifications.map(item=>{const read=state.readNotificationIds.includes(item.id);return <button className={`notification-row ${read?"is-read":""}`} onClick={()=>dispatch({type:"read-notification",notificationId:item.id})} key={item.id} type="button"><span className="notification-icon"><Bell size={19}/></span><span><strong>{item.title}</strong><small>{item.detail} · {item.time}</small></span>{!read?<i/>:null}</button>})}</div></div>; }

export function PhotographerScreen({ locale }: {readonly locale:Locale}) { const {state,dispatch}=useMockApp();const followed=state.followedPhotographerIds.includes("maya-velocity");return <div className={`${shell} max-w-4xl`}><section className="premium-card overflow-hidden"><img className="h-56 w-full object-cover" alt="Maya photographing vehicles on a scenic road" src="/media/hero-road.webp"/><div className="flex flex-wrap items-center gap-4 p-5"><Avatar initials="MV" large/><div className="mr-auto"><p className="premium-kicker">@maya.velocity</p><h1 className="text-2xl font-black">Maya Velocity</h1><p className="text-sm text-muted-foreground">Vehicle photographer · Bangkok</p></div><button className="primary-action inline-flex items-center gap-2" onClick={()=>dispatch({type:"toggle-follow",photographerId:"maya-velocity"})} type="button"><UserPlus size={18}/>{followed?(locale==="th"?"กำลังติดตาม":"Following"):(locale==="th"?"ติดตาม":"Follow")}</button></div></section><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{["/media/trip-lake.webp","/media/vehicle-car.png","/media/garage-bike.webp","/media/vehicle-bicycle.png"].map((src,index)=><img alt="Vehicle photography" className="aspect-[4/3] w-full rounded-2xl border border-border object-cover" src={src} key={index}/>)}</div></div>; }

function PageHeading({eyebrow,title,detail}:{eyebrow:string;title:string;detail:string}){return <div><p className="premium-kicker">{eyebrow}</p><h1 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{detail}</p></div>}
function Avatar({initials,large=false}:{initials:string;large?:boolean}){return <span className={`avatar ${large?"is-large":""}`} aria-hidden>{initials}</span>}
function vehicleIcon(kind:"all"|VehicleKind){if(kind==="car")return <Car size={17}/>;if(kind==="motorcycle")return <Motorcycle size={17}/>;if(kind==="bicycle")return <Bicycle size={17}/>;return <ShoppingBagOpen size={17}/>}
function capitalize(value:string){return value.charAt(0).toUpperCase()+value.slice(1)}
