export const navigationLabels = {
  th: {
    home: "หน้าหลัก",
    maps: "แผนที่",
    search: "ค้นหา",
    create: "สร้าง",
    profile: "โปรไฟล์",
    notifications: "แจ้งเตือน",
    menu: "ตั้งค่า",
    close: "ปิด",
    settings: "การตั้งค่า",
    language: "ภาษา",
    theme: "ธีม",
    light: "สว่าง",
    dark: "มืด",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    manageUsers: "จัดการผู้ใช้",
  },
  en: {
    home: "Home",
    maps: "Maps",
    search: "Search",
    create: "Create",
    profile: "Profile",
    notifications: "Notifications",
    menu: "Settings",
    close: "Close",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    login: "Sign in",
    logout: "Sign out",
    manageUsers: "Manage users",
  },
} as const;
